name: import_order_lint
description: "A custom lint plugin for enforcing import order in Dart files."
version: 0.1.4
repository: https://github.com/anusii/import-order-lint

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  args: ^2.4.2
  path: ^1.8.0
  yaml: ^3.1.3
  # Note: analyzer and custom_lint_builder removed - no longer needed for standalone tool

executables:
  import_order: import_order
  # Note: fix_imports removed - import_order is now the main executable

dev_dependencies:
  flutter:
    sdk: flutter
  test: ^1.24.0
