name: import_order_lint
description: "A custom lint plugin for enforcing import order in Dart files."
version: 0.2.1
repository: https://github.com/anusii/import-order-lint

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  args: ^2.4.2
  path: ^1.8.0
  yaml: ^3.1.3

executables:
  import_order: import_order

dev_dependencies:
  flutter:
    sdk: flutter
  test: ^1.24.0
